service: lambda-helper

provider:
  name: aws
  runtime: nodejs8.10

functions:
  echo:
    cljs: lambda-helper.core/echo
    events:
      - http:
          path: echo
          method: post
  hello:
    cljs: lambda-helper.core/hello
    events:
      - http:
          path: hello
          method: get
  hello-query:
    cljs: lambda-helper.core/hello-query
    events:
      - http:
          path: hello-query
          method: get
          request:
            parameters:
              querystrings:
                name: false

plugins:
  - serverless-cljs-plugin
